filetype plugin on
se nu
" ugly fix. searching python interpreters makes long startup time
let g:loaded_python_provider = 1
if has('macunix')
  let g:python3_host_prog = '/usr/local/bin/python3'
endif

let g:vimsyn_embed = 'l'

set termguicolors
set background=dark
let g:quantum_black=1
let g:quantum_italics=1
highlight MatchParen cterm=bold ctermbg=none ctermfg=magenta guibg=NONE guifg=Magenta
" onedark.vim override: Don't set a background color when running in a terminal;
" just use the terminal's background color
" `gui` is the hex color code used in GUI mode/nvim true-color mode
" `cterm` is the color code used in 256-color mode
" `cterm16` is the color code used in 16-color mode
if (has("autocmd") && !has("gui_running"))
  augroup colorset
    autocmd!
    let s:white = { "gui": "#ABB2BF", "cterm": "145", "cterm16" : "7" }
    " `bg` will not be styled since there is no `bg` setting
    autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": s:white })
  augroup END
endif
colorscheme onedark

set mouse=a
set colorcolumn=80
highlight CursorLine guibg=#303030
highlight VertSplit  guibg=#303030
if has("mac") | hi Normal guibg=None | endif
set shiftwidth=4
set softtabstop=4
set expandtab
set display+=lastline
set incsearch
set updatetime=300
let mapleader = ","
cnoreabbrev W w
nnoremap <silent> <C-N> :nohlsearch<cr>
nnoremap Q <Nop>
nnoremap vv $v^
nnoremap / /\v


xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

set pastetoggle=<Leader>p
" Bufferline
nnoremap <silent> <M-n> :bnext<CR>
nnoremap <silent> <M-p> :bprev<CR>

nmap <M-1> <Plug>BufTabLine.Go(1)
nmap <M-2> <Plug>BufTabLine.Go(2)
nmap <M-3> <Plug>BufTabLine.Go(3)
nmap <M-4> <Plug>BufTabLine.Go(4)
nmap <M-5> <Plug>BufTabLine.Go(5)
nmap <M-6> <Plug>BufTabLine.Go(6)
nmap <M-7> <Plug>BufTabLine.Go(7)
nmap <M-8> <Plug>BufTabLine.Go(8)
nmap <M-9> <Plug>BufTabLine.Go(9)
nmap <M-0> <Plug>BufTabLine.Go(10)

function! Bufferline()
  call bufferline#refresh_status()
  return [
        \ g:bufferline_status_info.before,
        \ g:bufferline_status_info.current,
        \ g:bufferline_status_info.after
        \]
endfunction

function! NearestMethodOrFunction() abort
  return get(b:, 'vista_nearest_method_or_function', '')
endfunction

let g:node_client_debug = 0

" nnoremap <leader>m :CocList<cr>
nmap <leader>ac <Plug>(coc-codeaction)
nmap <leader>dg <Plug>(coc-diagnostic-info)
" nmap <leader>gt <Plug>(coc-action-doHover)
nmap <leader>sn <Plug>(coc-action-showSignatureHelp)
nmap <leader>cl <Plug>(coc-codelens-action)
nmap <leader>ji <Plug>(coc-implementation)
nmap <leader>jd <Plug>(coc-definition)
nmap <leader>jr <Plug>(coc-references)
nmap <leader>fx <Plug>(coc-fix-current)
nmap <leader>ft <Plug>(coc-format-selected)
vmap <leader>ft <Plug>(coc-format-selected)
nmap <silent>[w <Plug>(coc-diagnostic-prev)
nmap <silent>]w <Plug>(coc-diagnostic-next)
nmap <silent>[e <Plug>(coc-diagnostic-prev-error)
nmap <silent>]e <Plug>(coc-diagnostic-next-error)
nmap <leader>rn <Plug>(coc-rename)
inoremap <silent><expr> <C-X><C-O> coc#refresh()
nnoremap <silent><space> :call CocActionAsync('doHover')<cr>
command! -nargs=0 Format :call CocAction('format')  " format the whole buffer

nnoremap <unique> <silent> <LocalLeader>l :<C-u>CocFzfList<CR>
nnoremap <unique> <silent> <LocalLeader>c :<C-u>CocFzfList commands<CR>
nnoremap <unique> <silent> <LocalLeader>d :<C-u>CocFzfList diagnostics --current-buf<CR>
nnoremap <unique> <silent> <LocalLeader>o :<C-u>CocFzfList outline<CR>
nnoremap <unique> <silent> <LocalLeader>s :<C-u>CocFzfList symbols<CR>

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')

  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction


augroup highlight_yank
    autocmd!
    au TextYankPost * silent! lua vim.highlight.on_yank { higroup='IncSearch', timeout=200 }
augroup END


syntax keyword pythonTodo contained NOTE NOTES
syntax keyword schemeSyntax λ

cnoreabbrev Fix ALEFix

augroup file_type
  au!
  " Alternative: au FileType python AutoFormatBuffer autopep8
  " au FileType c,cpp,proto AutoFormatBuffer clang-format

  " au Filetype python nmap <LocalLeader>rn :Semshi rename
  au BufRead *.rkt se ft=racket
  au BufRead flake.lock se ft=json
  " au FileType python set equalprg=autopep8\ -
  au FileType scheme let b:AutoPairs = {"(": ")"}
  au Filetype python set keywordprg=pydoc3
  au FileType python hi semshiImported ctermfg=214 guifg=#aaaaaa cterm=bold gui=bold
  au FileType python setlocal foldmethod=marker
  au FileType python,java setlocal shiftwidth=4 tabstop=4
  au FileType haskell hi Structure guifg=#00ffaf
  au FileType haskell hi Type      guifg=#61afef
  au FileType rust hi CocHintSign      guifg=Gray
  au FileType nasm,applescript,cmake,make set omnifunc=syntaxcomplete#Complete
  au FileType cpp set makeprg="cmake --build build"
  au FileType markdown set textwidth=80
  au FileType scheme inoreabbrev lambda λ

  au FileType typescript,typescript.jsx,javascript,cpp,haskell,go,cabal setlocal shiftwidth=2 tabstop=2
  "au FileType typescript :syn clear jsxAttrib
augroup END

" very slow
" au FileType python se foldmethod=expr | se foldexpr=nvim_treesitter#foldexpr()

let g:neomake_cmake_maker = {
      \ 'name': 'cmake',
      \ 'exe': 'cmake',
      \ 'args': ['--build'],
      \ 'append_file': 0,
      \}
" let g:neomake_cpp_enabled_makers = ['cmake', 'makeprg']

nnoremap <Leader>e :CocCommand explorer <CR>

" clear italic
hi CocExplorerIndentLine cterm=NONE guifg=#303030

nnoremap <silent> <leader>q  :bp\|bd #<CR>

nnoremap <C-P> :FZF<CR>


" Required for operations modifying multiple buffers like rename.
set hidden
set noshowmode  " Don't show INSERT/NORMAL... mode in cmdline
set completeopt-=preview


let g:qs_lazy_highlight = 1  " QuickScope
let g:gitgutter_signs = 0
autocmd CursorHold * CocCommand git.refresh  " in case gutters may not update

" navigate chunks of current buffer
" don't lie vim-fugitive
nmap [c <Plug>(coc-git-prevchunk)
nmap ]c <Plug>(coc-git-nextchunk)
" show chunk diff at current position
nmap <Leader>d <Plug>(coc-git-chunkinfo)
nnoremap <Leader>a :CocCommand git.chunkStage<CR>
nnoremap <Leader>u :CocCommand git.chunkUndo<CR>

omap ig <Plug>(coc-git-chunk-inner)
xmap ig <Plug>(coc-git-chunk-inner)
omap ag <Plug>(coc-git-chunk-outer)
xmap ag <Plug>(coc-git-chunk-outer)

" highlighting
" let g:haskell_enable_quantification   = 1  " `forall`
" let g:haskell_enable_recursivedo      = 1  " `mdo` and `rec`
" let g:haskell_enable_arrowsyntax      = 1  " `proc`
" let g:haskell_enable_pattern_synonyms = 1  " `pattern`
" let g:haskell_enable_typeroles        = 1  " type roles
" let g:haskell_enable_static_pointers  = 1  " `static`
" let g:haskell_backpack                = 1  " backpack keywords

function! s:delete_trailing_white_spaces()
  %s/\s\+$//ge
endfunction
command! DeleteTrailingWhiteSpaces call s:delete_trailing_white_spaces()

function! s:syntax_query() abort
  for id in synstack(line("."), col("."))
    echo synIDattr(id, "name")
  endfor
endfunction
command! SyntaxQuery call s:syntax_query()

" bracketed paste
if &term =~ '\(alacritty\|xterm.*\)'
    let &t_ti = &t_ti . "\e[?2004h"
    let &t_te = "\e[?2004l" . &t_te
    function! XTermPasteBegin(ret)
        set pastetoggle=<Esc>[201~
        set paste
        return a:ret
    endfunction
    map <expr> <Esc>[200~ XTermPasteBegin("i")
    imap <expr> <Esc>[200~ XTermPasteBegin("")
    vmap <expr> <Esc>[200~ XTermPasteBegin("c")
    cmap <Esc>[200~ <nop>
    cmap <Esc>[201~ <nop>
endif

function! s:convert__snake_case__to_camelCase()
  s#_\(\l\)#\u\1#g
endfunction
command! SnakecamelCase call s:convert__snake_case__to_camelCase()

function! s:convert__snake_case__to_CamelCase()
  s#_\(\l\)#\u\1#g
endfunction
command! SnakeCamelCase call s:convert__snake_case__to_camelCase()
