name: 0

windows:
    - batmobile:
        layout: main-vertical
        pre: cd ~/dev/batmobile && nix develop --command $SHELL --login
        panes:
            -
            -
    - simplenote:
        panes:
            - sncli

    - personal:
        panes:
            - cd ~/dev

# vim: shiftwidth=4 tabstop=4:
