name: 0

windows:
    - batmobile:
        layout: main-vertical
        pre: cd ~/dev/batmobile && nix develop
        panes:
            -
            -
    - simplenote:
        panes:
            - node -v && sncli

    - personal:
        panes:
            - cd ~/dev && node -v > /dev/null

# vim: shiftwidth=4 tabstop=4:
