name: 0

startup_window: simplenote
windows:
    - batmobile:
        layout: 393b,295x75,0,0{209x75,0,0,0,85x75,210,0,3}  # big left
        pre: cd ~/dev/batmobile && nix develop --command $SHELL --login
        panes:
            -
            -
    - simplenote:
        panes:
            - sncli

    - personal:
        panes:
            - cd ~/dev

    - vpn:
        panes:
            - test -f ~/vpn/vpn.sh && cd ~/vpn && ./vpn.sh

# vim: shiftwidth=4 tabstop=4:
