name: 0

startup_window: simplenote
windows:
    - personal:
        panes:
            - cd ~/dev

    - work:
        pre: cd ~/dev/speedify
        panes:
            -

# vim: shiftwidth=4 tabstop=4:
